import { SERVICE_VERSION } from '@openworkgraph/protocol';

export function formatHelp(): string {
  const row = (syntax: string, description: string) => '  ' + syntax.padEnd(32) + description;
  return [
    '',
    'OpenWorkgraph  ' + SERVICE_VERSION,
    'Local workflow service',
    '',
    'Usage',
    '  openworkgraph <command> [options]',
    '',
    'Service management',
    row('start', 'Start in the background'),
    row('restart', 'Restart the service; acts as start when it is not running'),
    row('update', 'Stop the service, install the latest package, and restart it if it was running'),
    row('serve', 'Run in the foreground'),
    row('status', 'Show service status'),
    row('logs', 'Show service logs'),
    row('stop', 'Wait for active tasks, then stop; keep queued tasks'),
    row('capacity [COUNT]', 'Show or set concurrency (a positive integer)'),
    '',
    'Client pairing',
    row('pair --client-code <CLIENT_CODE>', 'Verify origin and fingerprint, then approve the client'),
    row('sessions', 'List client sessions'),
    row('revoke-session <SESSION_ID>', 'Revoke a session'),
    '',
    'Backup and restore',
    row('backup create', 'Create a backup'),
    row('backup list', 'List backups'),
    row('backup download <BACKUP_ID>', 'Download a backup; requires --output <NEW_FILE>'),
    row('restore preview <PATH>', 'Preview a restore and its SHA-256'),
    row('restore apply <PATH>', 'Restore locally; requires --sha256 <HASH>'),
    '',
    'Plugins',
    row('plugin register <MANIFEST>', 'Register a trusted plugin JSON manifest'),
    '',
    'Startup options · start / serve only',
    row('--data-dir <PATH>', 'Set and remember the service data directory'),
    row('--host <ADDRESS>', 'Listen address (default: 0.0.0.0)'),
    row('--port <PORT>', 'Listen port (default: 14317)'),
    '  restart accepts --host / --port overrides; if stopping takes over 10 seconds, check status.',
    '',
    'Other options',
    row('version', 'Show version'),
    row('--yes', 'pair: explicitly approve in non-interactive scripts'),
    row('--output-json', 'Output JSON for scripts and automation'),
    row('--interrupt-and-stop', 'stop / restart / update: legacy alias; stopping cancels active and queued tasks'),
    row('--idempotency-key <KEY>', 'backup create: set an idempotency key'),
    row('--help', 'Show help'),
    row('--version', 'Show version'),
    '',
    'Examples',
    '  openworkgraph start --host 127.0.0.1',
    '  openworkgraph pair --client-code 12345678',
    '  openworkgraph status',
    '  openworkgraph restart',
    '  openworkgraph update',
    '  openworkgraph backup create',
    '  openworkgraph stop',
    '',
  ].join('\n');
}
