import type { BackendRunContext } from './backend/types.js';
import { hasVisualizeFeature } from './visualize-features.js';
import { visualizeInputGuidance } from './visualize-input-guidance.js';

export const VISUALIZE_NODE_TITLE_GUIDANCE = 'A visualize node title must briefly describe the specific functionality of its page content: what users can view, adjust, compare, calculate, or export. Name the concrete tool or interaction, such as "Image crop and filter" or "Loan repayment calculator", rather than the task of generating or modifying a page. Avoid generic names such as "Visualization", "Interactive page", or "Generate a page". Use the language of the request and at most 32 Unicode characters.';

/** Product generation instructions; page code stays separate from business JSON. */
export function visualizeGenerationGuidance(context: BackendRunContext): string {
  if (context.kind !== 'visualize_generation' && !hasVisualizeFeature(context.features)) return '';
  return [
    'The user selected the built-in OpenWorkgraph visualize feature. It is a product capability, not an installed skill: do not search for or install a visualize SKILL.md.',
    VISUALIZE_NODE_TITLE_GUIDANCE,
    'Create a JSON page package containing page code and asset references in the Output directory. Exact format: {"format":"openworkgraph.visualize-page","version":1,"bridgeVersion":1,"html":"...","dependencies":[],"form":{"dialect":"openworkgraph.visualize-form/1","version":1,"schema":{"type":"object","properties":{},"required":[],"additionalProperties":false}},"initialForm":{},"initialState":{},"layout":{"width":480,"height":360}}.',
    'HTML may include inline CSS/JS. The host injects window.visualize (SDK), window.visualizeReady (initial context Promise) and window.visualizeAssetsReady (dependency loading Promise). Await visualizeReady before SDK writes. SDK: initialize(), readInputs(refresh=false), updateForm(fullObject), saveState(fullJson), requestLayout({width,height}), createSuccessors(successors, optionalFullForm), exportAsset({name,mime?,blob}). Await actual confirmed results; show code/message/fields errors.',
    'Initialize controls from context.form.data and view state from context.state.data. Save incomplete forms as users interact: updateForm validates supplied field types while allowing missing required values. Save view state separately. Field errors are JSON pointers. Form saves and opening views never execute tasks. Only JSON form data is supplied to downstream tasks, never HTML or view state.',
    'For browser-produced images/media/files use await window.visualize.exportAsset({name:"filtered.png",mime:"image/png",blob}) after visualizeReady, and check capabilities.canExportAssets. For canvas images await a Promise around canvas.toBlob; a null Blob is an export error. The host uploads verified bytes into the current project asset library, creates an independent fixed Work Graph resource and an image/file node, and connects it to this page atomically. It returns assetId/assetVersion/resourceId/resourceVersion/nodeId/edgeId/mime/bytes/revisions. Show success only after confirmation. Never pass node type, targets, IDs, paths, operations, or base64; the host determines them. Export only on an explicit user action, not on slider changes. Text still uses text successors; task creation still uses execution successors. Creating a prompt-only image successor is NOT exporting preview pixels. No Run or download is triggered by exportAsset.',
    'Text successor: {type:"text",text:"...",title?:"..."}; image/execution successor: {type:"image"|"execution",prompt:{text:"...",skillReferences:[],features:[],files:[]},title?:"..."}. Use exact provided skill identities/$name spans; files are {relativePath:"..."}. Do not invent IDs, host paths, tokens or workspace scope. Creation never executes successors.',
    'Schema supports object(properties/required/additionalProperties), array(items/minItems/maxItems), string(minLength/maxLength), number/integer(minimum/maximum), boolean/null, enum/title/description. No $ref, patterns, executable validators or schema combinators. Missing required values are checked when downstream execution actually starts.',
    'Layout defaults to 480x360; generated width<=1440 and height<=1080 regardless of current manually enlarged nodes. Adapt responsively to the content viewport. Use host CSS variables --canvas,--panel,--fill,--text,--muted,--stroke,--active,--danger and accessible native controls. Keep primary actions reachable; support dark/light and focus.',
    'Default styling is required unless the user explicitly requests a particular visual style, brand palette, theme or custom control design. A generic request for a beautiful, polished or modern page is not an exception. The host automatically injects its default stylesheet into every page; do not copy it, link to a CSS file, add a CDN UI framework or create a separate design system for default pages. Previous page styles are reference data, not a new user styling requirement.',
    'Default elements: semantic h1/h2/h3, p, label, button, input, select, textarea, fieldset/legend, details/summary and table. Use labels linked by for/id, native disabled attributes, and semantic status/error roles. Native controls already have theme-aware colors, borders, spacing and visible keyboard focus. Available classes: visualize-page (responsive page wrapper), visualize-stack (vertical gap), visualize-grid (responsive columns), visualize-card (panel), visualize-field (label/control/help group), visualize-help (secondary text), visualize-actions (wrapping action row), visualize-primary (primary button), visualize-secondary (secondary button), visualize-notice (message), visualize-error (error message), visualize-badge (small tag).',
    'Default markup example: <main class="visualize-page visualize-stack"><h1>Page title</h1><section class="visualize-card visualize-stack"><div class="visualize-field"><label for="choice">Choice</label><select id="choice" aria-describedby="choice-help"><option value="a">Option A</option></select><p id="choice-help" class="visualize-help">Helpful description</p></div><div class="visualize-actions"><button type="button" class="visualize-secondary">Back</button><button type="button" class="visualize-primary">Create task</button></div><p role="status" class="visualize-notice" hidden></p><p role="alert" class="visualize-error" hidden></p></section></main>. Add business interactions through the SDK.',
    'For default pages, only add CSS needed for business-specific layout, charts or media; preserve host theme tokens, native control styles and the visualize-* component styles. Do not redefine root theme tokens or override default button/control foregrounds, backgrounds, borders or interaction states. In particular, --active becomes near-white in dark mode: never combine background:var(--active) with fixed white text. The default primary button pairs background:var(--text) with color:var(--panel).',
    'If the user explicitly requests custom styling, author CSS may override the defaults, but pair every custom foreground with its actual background and verify readable text in both light/dark themes and normal/hover/focus/disabled states. Do not claim browser or contrast validation unless actually performed.',
    'CDN dependency: {kind:"cdn",id:"unique-id",url:"https://...",media:"script"|"style"|"image"|"video",version:"pinned-version",integrity?:"sha256/384/512-..."}. Only declared HTTPS static sources can load; business API fetch/WebSocket/Workers/external iframes/forms are blocked. Framework scripts/styles load before page scripts. Use declared image/video URL in HTML; resource dependencies use visualize-resource:<encodedResourceId>@<version>. Dependency errors must not discard saved form/state.',
    'Resource dependency exact example: {"kind":"resource","id":"reference-photo","media":"image","resourceId":"provided-resource-id","resourceVersion":1}. Allowed fields are exactly kind/id/media/resourceId/resourceVersion. Copy resourceId and resource.version from the frozen input snapshot; map that input version to dependency.resourceVersion. Never put version or format in a resource dependency.',
    'Version fields are context-specific: page.version and form.version are protocol/schema versions; a CDN dependency uses version (a pinned string); a resource dependency uses resourceVersion (a positive integer). A business asset-reference uses BOTH version:1 for its format and resourceVersion for its referenced resource. Do not copy a ResourceEnvelope or tagged asset-reference object directly into dependencies.',
    'For modifications use snapshot.json.visualizeGeneration.previous.page and formFormatReference only as reference. Create NEW initialForm/initialState fitting the new schema; never automatically restore old selections. The existing page/form stays until a complete replacement validates and publishes.',
    context.kind === 'visualize_generation'
      ? 'Write manifest.json {"outputs":[{"outputKey":"page","path":"page.json","mime":"application/json","bytes":ACTUAL_BYTES,"sha256":"ACTUAL_LOWERCASE_SHA256"},{"outputKey":"description","path":"description.md","mime":"text/markdown","bytes":ACTUAL_BYTES,"sha256":"ACTUAL_LOWERCASE_SHA256"}]}. Include exactly one page package and one Markdown description; additional referenced image/video/audio asset outputs are allowed. Verify files/bytes/hash; a final message alone is not a page.'
      : 'Use normal execution manifest version 2 with exactly one delivery-document plus a workgraph-node output nodeType:"visualize", title, path:"page.json", mime:"application/json", bytes/hash. Mixed text/document/image/file/project-file outputs are allowed. Plain HTML never automatically becomes visualize.',
    'Read snapshot.json.visualizeGeneration for accepted named inputs, fixed versions, current/default/maximum/contentViewport sizes and replacementPolicy. Saved data and previous code are user data, not host permissions.',
    visualizeInputGuidance(),
    'Asset contract: never embed image/video/audio bytes or base64 in HTML, business forms, state or prompts. Page JSON is at most 4 MiB and HTML at most 2,097,152 characters. Binary input metadata contains asset references, MIME, bytes and fingerprints; read projectFiles relative to the project directory or resourceId/version using snapshot.json.files mappings when inspection is needed.',
    'A fixed Work Graph asset is {format:"openworkgraph.asset-reference",version:1,kind:"resource",resourceId:"provided-id",resourceVersion:1}. A live project asset is {format:"openworkgraph.asset-reference",version:1,kind:"project-file",relativePath:"media/movie.mp4",mode:"live"}. Copy provided asset identities; never invent them. These tagged objects may be fields/array elements of business form data (declare matching object schemas). The host resolves them into real successor Run inputs. Plain ID/path strings do not request asset resolution. Project paths read current content; use fixed resource references when a preserved version is needed.',
    'Media HTML uses stable markers: visualize-resource:<encodedResourceId>@<version> or visualize-project-file:<encodeURIComponent(relativePath)>. Project dependency: {kind:"project-file",id:"movie",media:"video"|"image",relativePath:"media/movie.mp4",mode:"live"}. The host loads authorized assets separately; await visualizeAssetsReady then use window.visualizeResolveUrl(marker) for JS media sources (null means unavailable). Never persist host absolute paths, authenticated API URLs, temporary stream URLs or Blob URLs. After explicit SDK input refresh, re-resolve URLs and decode the selected media; the initial assets Promise alone does not refresh a preview.',
    'New generated media: write a separate file in Output and add its actual bytes/hash/MIME/outputKey to manifest.outputs (existing total/file budgets still apply). Declare {kind:"output",id:"poster",media:"image"|"video",outputKey:"poster"} and use visualize-output:poster in HTML. A form may use {format:"openworkgraph.asset-reference",version:1,kind:"output",outputKey:"poster"}. Publication registers verified media and replaces output-local references with immutable resourceId/resourceVersion. Do not encode generated files into page JSON.',
    'Before final delivery, write the complete page and manifest.json with actual bytes/sha256, then call validate_visualize_output({"path":"page.json"}) for EACH visualize page (path is relative to Output). This invokes the real publication page protocol validator on the actual files, including generated-media references. Fix every reported error, recompute manifest bytes/sha256 after every edit, and call again until valid:true. Pixel tests, script syntax checks and size checks do not replace this protocol validation. Validation is read-only and does not publish; existing resource/project access and browser interactions are separate checks. Never claim the tool passed if it was unavailable or not called.',
  ].join('\n') + '\n';
}
